[package]
name = "get-request"
version = "0.1.0"
edition = "2021"

[dependencies]
error-chain = "0.12.4"
reqwest = {version = "0.12.5", features = ["json", "blocking"]}
tokio = { version = "1.39.2", features = ["full"] }
